### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by meian** [meian/gcf#3]
Github Actionsで以下の辺り？

- fmt
    - go fmtかけて変更ある場合は落とす
- test
- ~coverage~
    - 手間かかりそうなので別issueに切り出した
- static check
     - 何かいいのあれば導入する

RCのイメージ使ってできるかも一応確認、ダメなら正規イメージ出てから

**Comment by meian** [comment]
https://github.com/actions/setup-go

> Matching an unstable pre-release:

```yaml
steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-go@v2
    with:
      stable: 'false'
      go-version: '1.14.0-rc1' # The Go version to download (if necessary) and use.
  - run: go version
```

これで行けそうなので試してみる
